### PR TITLE
If we re-obtain a star system from the server, remember it.

### PR DESCRIPTION
**Pull request by Tkael**
Also, less verbose logging when we do this.

### CODE REVIEW

**Comment by Tkael** [comment]
Please include with 3.0.1.

**Comment by richardbuckle** [comment]
Sorry, I think we have to consider 3.0.1 locked down now.

**Comment by richardbuckle** [comment]
I am always happy to discuss my milestone allocations, but please do not undo them unilaterally.

**Comment by Tkael** [comment]
The point of an RC is to fix bugs. I labeled this as a back-end improvement since it's not user facing, but I do consider this to be a back-end bug fix with nill risk (and thus appropriate for 3.0.1).

**Pull request merged**
