### PR TITLE
Enhance access to the Script resolver from VoiceAttack, improve documentation

### PR DESCRIPTION
**Pull request by Tkael**
- Text from the VoiceAttack plugin is now passed through our EDDI's script resolver, making all of EDDI's Speech responder functions invokable from VoiceAttack.
- VoiceAttack-Integration.md updated for clarity and to document previously undocumented plugin functions (particularly `route` and `jumpdetails`). 

@Hoodathunk , I'm not sure that I've got everything right with respect to the  `route` and `jumpdetails` plugin commands so please look these over and let me know if and where I might need to make adjustments.

### CODE REVIEW

**Comment by richardbuckle** [comment]
Wow, this is quite a big one.

**Comment by richardbuckle** [comment]
Looks good but I think it deserves a more careful review.

**Comment by alterNERDtive** [comment]
\*nervously twiddles his thumbs waiting for the reviews\*

**Comment by Tkael** [comment]
Closing to rebase.

**Pull request closed without merging**
