### PR TITLE
Feature/material record

### LINKED ISSUE #1914: Planetary material percentages need update
## EDDI version in which issue is found
3.7.0

## Expected
The current good and great percentages in Material.cs need to be updated, because this data is 3 years old.

To be specific, I gave Jgm on the in March 2017 [this spreadsheet](https://docs.google.com/spreadsheets/d/1UcgHvnDF-lYYPD7PNkT_g7B1dr9lBBkVPPlL51ITrz4/edit#gid=0) which I used then to [document top records](https://forums.frontier.co.uk/threads/prospection-farm-locations-for-engineers-jumponium.302833/). He used it to implement voice feedback discoveries on body scans.

One should note I did a simple interpretation back then: find the top record, calculate top 10% and top 25%.

Updating it "as-is" should be done without outliers, since currently no percentiles or normal distributions are used. Another ticket will be created to tackle percentiles.

## Investigation

Just learned spansh.co.uk search should be used to find top records.

### LINKED ISSUE #1916: Introduce event for planetary material record
## EDDI version in which issue is found
3.7.0

## Expected
When a new record is found, EDDI notifies you broke the current record.

For example, let's say you find a planet with a Polonium percentage higher then the current record of 2.093%. Currently EDDI will treat this as a great percentage event, so any finding at 1.3% or higher will result in the same audio feedback. Instead, we'd like EDDI to treat this record as a separate event, giving it a specific message.

## Investigation
EDSM does not keep records for material distributions, so static values will have to be kept and maintained. Possible configurable from scripts?

### PR DESCRIPTION
**Pull request by Javelias**
Resolves #1914 and resolves https://github.com/EDCD/EDDI/issues/1916
Alternative to #1912 (merge only one).

### CODE REVIEW

**Comment by Tkael** [comment]
1. With respect to updating percentiles - I recognize that this is the same approach used in 2017 but I prefer the approach proposed in #1917. The current method used for these calculations sets "good" and "great" to 25% or 10% of the "top" value but since the current method doesn't model distributions and since distributions may not be equal from one material to the next the current method can provide an inconsistent experience which varies from one material to the next. 
2. The team may disagree but if we're going to generate an event declaring a galactic record then I think it needs to be based on a value that is being tracked on a server. I'm not comfortable with hard coding "record" values into the program and I think that it sets a bad precedent where we'll need to continually monitor and update the hard coded values into the future.

**Comment by Javelias** [comment]
I agree with both your comments.

1. I assumed this as a temporary solution before #1917, I feel that one will take some time to get right (I noticed it's a 3.2TB data file to parse through).

2. Didn't like hard-coding either, felt bad indeed, on the flip side, material.cs already was using hard-coded values, so didn't feel like it made a difference.

Essentially this was a quick-win to bridge the time for not having #1917 nor an endpoint EDSM API as requested in https://github.com/EDSM-NET/FrontEnd/issues/369.

**Review by GioVAX — APPROVED** [review]
LGTM, with the understanding that this is a temporary fix while we work out #1917.

**Comment by Tkael** [comment]
For "bridging the gap", I'd prefer to go with #1912 as the simpler bridge.

**Comment by Javelias** [comment]
For me that's fine.

**Comment by Tkael** [comment]
Closing in preference to #1912.

**Pull request closed without merging**
