### PR TITLE
Update Frontier API user agent

### LINKED ISSUE #644: Use more identifiable user agent when requesting data from the Frontier API
Posted by OtisB from EDMC in the EDCD developers discord:
```
FYI it's now no longer required to fake up an iPhone User-Agent string in order to use the cAPI. Forwarded from Dav @ FDev:
 "I'd be delighted if the user agents were simply along the lines of "EDCD-MyAppName-12.34.45" without any of the other parts of it."
So e.g. next version of EDMC will set the User-Agent string to "EDCD-EDMarketConnector-3.0.7.0"
```

### PR DESCRIPTION
**Pull request by Tkael**
Resolve #644

### CODE REVIEW

**Comment by Tkael** [comment]
Per Fdev Rhevian: `The regex is: EDCD-[A-Za-z]+-[.0-9]+`
The Frontier API did seem to accept the PR'd change to the user agent, though it may have been capturing it less `-rc1`?

**Comment by Tkael** [comment]
Placing on hold due to partial incompatibility with FDev's regex. Thoughts?

**Comment by Tkael** [comment]
Notably, the full release is compatible but the `rc1` suffix on the current build is not.

**Comment by richardbuckle** [comment]
Superseded by #801.

**Pull request closed without merging**
