### PR TITLE
Allow user to disable TTS voice effect based on used ship.

### PR DESCRIPTION
**Pull request by rblanker**
In short, I don't like the TTS voice in EDDI and how it uses the type of ship to change the TTS voice.  You can put it to very low, but the difference is still noticeable. I also use a lot of TTS in VoiceAttack and want to divert all TTS to EDDI instead of VA TTS.  But then I get this changed TTS voice that I don't like. So added the option to disable it. The ship voice is enabled by default, so normal users will not notice anything until they disabled it.

- Added checkbox 'Disable ship effects on voice:' on the 'Text-to-speech' tab.
- English text only.
- The option is off by default (allow ship effects).

Tiny fix:
- Removed margin from Volume of speech slider, because when putting all sliders
  in the middle (50, 0, 50), volume of speech slider didn't align (and was a
  few pixels shorter next to the input box).

### CODE REVIEW

**Comment by rblanker** [comment]
Yeah, you are right. The transmit and radio, I saw that in the code, was not sure if that had anything to do with the ship effect. I thought it was fine, because a ship default was chosen if none was set, that the effect was meant for the ship. I will make some changes to exclude transmit and radio when its disabled. 

I did notice the gain with volume a bit when putting the effect on 0, but the difference with TTS in VA and TTS in EDDI is too much. I kinda like the way that I can control what voice is used with TTS in VA, but I haven't found a way to tell EDDI to use my voice for all its TTS  (from that point on) without changing it in EDDI (it might be possible?). 

Also the new queuing system in VA now allows more streamlined text and priority just like EDDI can do. I think a great feature would be to let EDDI sent the TTS directly back to VA (as option) and let it handle the priority and queuing. It will also allow VA to add/insert text on the generated TTS text when events are triggered. VA can ask questions on events, like 'Do you wish to scan the system?', when its your first visit (I have scripts in VA that starts FSS and scans the system). But you can only do that when EDDI stops talking right after the jump. You can't sent the text to EDDI either because you have no idea when the question is spoken unless you put priority to 1. Anyway, is a bit off topic :) Love EDDI btw.

Thank you for the feedback.

**Comment by Tkael** [comment]
Check out the `voice` parameter on the `say` and `speech` plugin context. https://github.com/EDCD/EDDI/wiki/VoiceAttack-Integration#say

As for the queuing system, the Speech Responder and VoiceAttack Responder currently operate independent of one another. What you're describing sounds rather complicated and may be best left in VoiceAttack's domain. In any case, let's stay focused on the issue at hand.

**Comment by rblanker** [comment]
Was a simple adjustment, it will allow 'transmit' of the radio voice when ship effects are turned off. 

I didn't know this was possible with EDDI, nice feature. 

Thank you.

**Comment by Tkael** [comment]
Hi Robert, I still feel like this concern can be resolved more simply
- If we focus in SpeechFX.cs, there's no need to add a checkbox in the UI. Slight adjustments to existing methods would ensure that speech effects are not applied while the level of voice processing is zero. 
- I think that it is confusing and inconsistent to apply voice effects (which are designed to make the voice sound more synthetic) to transmitted audio but not to ship audio. Aside from the specific radio effects, the ship's basic voice should be consistent whether in ship or transmitted over radio.
- Your solution still omits the audio gain adjustment that we normally perform. I believe that we should keep that in-place. 

All that being said, I'll submit an alternate PR to consider in place of this one. 

Note: Without this PR and when voice processing is zero, the only effects being applied to the voice are currently a slight echo effect (5% wet/dry mix) and the audio gain adjustment (which you can already address in your setup by adjusting EDDI's volume).

**Comment by rblanker** [comment]
I agree, this is a better approach. The checkbox was for me to make sure that I didn't break anything, taken the issue with transmit aside. I can live with the slight echo, I now can use EDDI TSS instead of VA TTS. Maybe at some point we can make all the effects editable per ship, that would be a great feature for the future. Thank you.

**Comment by Tkael** [comment]
That is something to consider. I'll go ahead and close this in favor of #1675, but thank you for your feedback / PR.

**Comment by richardbuckle** [comment]
Merged #1675. Thanks @rblanker for the initial PR!

**Pull request closed without merging**
