### PR TITLE
Re-target for .Net Framework version 4.8

### PR DESCRIPTION
**Pull request by Tkael**
Tested in standalone and in VoiceAttack. Includes some minor bug fixes identified during testing. Re-enables virtualization in the Speech Responder WPF datagrid.

### CODE REVIEW

**Comment by richardbuckle** [comment]
Does this help #1449 and #1236 ?

**Comment by Tkael** [comment]
> 
> 
> Does this help #1449 and #1236 ?

#1449 - Yes, though we may still want to take JPVenson up on his offer to re-write and optimize this section of the code. 
#1236 - No.

**Comment by JPVenson** [comment]
I am glad to help, as I currently do not have a project to work on. If you want to rewrite the apps UI with MVVM and related technology I could coordinate and provide resources for that as well as leading this change.

**Comment by Tkael** [comment]
I'm certainly interested. I've watched a number of YouTube tutorials covering some of the basics and your training materials look like they will be quite helpful as well.

MVVM might be a helpful tool for resolving #1236 & #1576.

**Comment by Tkael** [comment]
The materials you've provided have already been quite educational for me. In particular, it looks like the PDF is going help resolve some of the concerns I've had around implementing controls and events.

If you're interested in submitting a PR modeling how you would apply MVVM to just one of our monitors or responders then I think that would be quite helpful (though I wouldn't want to ask you to take on the entire UI until we've had a chance to study the approach further). 

Do I have your permission to share these materials with @richardbuckle on our private Discord channel? I trust him to respect your request to keep the materials private.

I hope I'm not over-stepping, but I ran across a couple of apparent typos while reviewing the materials. 
- On Powerpoint slide 8, "occures" perhaps should be "occurs". 
- On Powerpoint slide 17, "RaiseProeprtyChanged" perhaps should be "RaisePropertyChanged"
- On Powerpoint slide 18, "Fassade" perhaps should be "Facade"
- On PDF page 11, "capter" perhaps should be "chapter"
- On PDF page 19, "AssosiatedObject" perhaps should be ["AssociatedObject"](https://docs.microsoft.com/en-us/previous-versions/visualstudio/design-tools/expression-studio-4/ff726364(v=expression.40))

**Comment by JPVenson** [comment]
Quite interesting isn`t it?

Sure I will rewrite some View with MVVM and explain the changes in a PR extensively. 

OK you may share the documents with him.

No please go ahead, as a non-native speaker I am eager to have spelling mistakes to be rooted out. (you are the first one in 5 years who does seem to notice tho :-D)

**Pull request merged**
