### PR TITLE
Vertical blank fix 107

### PR DESCRIPTION
**Pull request by richardbuckle**
I am working in an area of the code that I'm not yet conversant with, so please review carefuilly. 

After much testing of landable and non-landable bodies with and without DSS I couldn't find a reliable test for null in Cottle so opted for only saying anything if `landable` is true.

A Cottlle expert may be able to do better.

### CODE REVIEW

**Comment by Hoodathunk** [comment]
Here you go...

`
    {if type(reportbody.landable) != "void":
        that is

        {if reportbody.landable:
            suitable
        |else:
            unsuitable
        }
        for landing.
    }

`

**Comment by richardbuckle** [comment]
Cheers Hoodathunk, pushed that change to this branch and will give it a quick test.

**Comment by Hoodathunk** [comment]
One last comment.

Reasonably sure you didn't add this but I don't see how this will work as intended:

|elif state.eddi_context_nav_scans &&  state.eddi_context_nav_scans > 0:
   {_ Do nothing if this scan is part of a nav beacon scan _}

There is no mechanism for state.eddi_context_nav_scans to be reset to null or zero. Additionally, this is unnecessary as the speech responder ignores Nav Beacon generated scan events.

**Comment by richardbuckle** [comment]
Ah I copied that one in assuming it was a necessary change. I'll take it out.

**Comment by Hoodathunk** [comment]
Okie dokie... I'm good then.

**Comment by richardbuckle** [comment]
Took out the spurious `state.eddi_context_nav_scans` tests and re-enabled the data voucher event which had been disabled somehow.

Just awaiting sign-off by @Hoodathunk and @Tkael

**Comment by Tkael** [comment]
I'll take another look at this tonight.why are we certain the original code was recording null as false?

**Comment by Tkael** [comment]
You're also still changing Body scanned from 
`"default": true,`
to
`"default": false,`
I'm not sure why?

**Comment by richardbuckle** [comment]
Default amended to true, good catch.

Totally certain the original code was recording null as false because it if you scanned a landable w/o a DSS it was saying it was non-landable. Also reported by end users in the forums.

**Comment by richardbuckle** [comment]
I have tested this in 2.4 live with and w/o a DSS and it is now working as designed.

**Comment by Tkael** [comment]
According to that assertion, with the develop branch this cottle script should always return either true or false on a body scan, even without a DSS installed?
`Body property: 'landable' is {if event.landable = null: null |else: {event.landable} }`
Without a DSS installed, the response I got from a test scan was 
`Body property: 'landable' is **null**`

This change may be perfectly valid, but it does not seem to be necessary for distinguishing between false & null. The original C# code distinguishes. It's just in Cottle that we need to make an adjustment.

For example, Hoodathunk's code
```
{if type(reportbody.landable) != "void": that is
    {if reportbody.landable:
        suitable
    |else:
        unsuitable
    }
    for landing.
}
```
works just fine with the current develop branch.

**Comment by richardbuckle** [comment]
I just tested this with the develop branch and Tkael is right. We only needed to change the Cottle script. This is because the value type of the dictionary isn't `bool`, it's `object`. So I gets set to `null` not `false` if the key is not found. If I had done proper TDD and tried to write a failing test before coding anything I would have seen this.

That said, I still prefer my implementation of `getOptionalBool` as I think it is easier to understand.

**Pull request merged**
