### PR TITLE
Correct expiry to seconds rather than DateTime

### PR DESCRIPTION
**Pull request by Tkael**

### CODE REVIEW

**Comment by richardbuckle** [comment]
What issue is this referencing please? 

I always go on yellow alert when date/time stuff crops up! 

I am eager to get a complete understanding of the use case. While I can well understand an ephemeral TTS use case for the current seconds to expiry, the DateTime value is more suitable for writing to storage. 

I just want to double-check that the usage will be merely ephemeral.

**Comment by Tkael** [comment]
Undocumented issue. Darkcyde mentioned on discord that he'd tested the variables in the CommunityGoal event but that event.expiry appeared to not be set. It turns out that neither Cottle nor VoiceAttack can really handle DateTime variables, so switching to seconds made more sense. Furthermore, time variables that are already presented to the user are consistently presented in seconds.
See for example the SecondsSince() function and variables like system.updatedat, which all operate in terms of seconds. The DateTime format is only used for admin functions like timestamps.

Note that this actually prevents event.timestamp from being used at all by the end user. I explored creating a Cottle function for converting from DateTime to seconds, but realized that would leave VoiceAttack users without access to the same information. Also, I couldn't get it to work right. ;-)  

The revision allows the cottle script to become sensitive to the time remaining. I've updated the cottle script to let users know that a community goal will be ending soon if there are less than 12 hours left. :-)

**Comment by Tkael** [comment]
Resolved changelog.md

**Comment by richardbuckle** [comment]
Fair enough. Just wanted to probe that you had considered the issues.

**Pull request merged**
