### PR TITLE
Ship Role hotfix

### PR DESCRIPTION
**Pull request by Hoodathunk**
Hotifx to properly populate ship.role property and ensure persistence across EDDI sessions.

Note:
Using ``` public static readonly Role MultiPurpose;``` definitions, while syntactically correct, the compiler allows assignments such as ```Role = Role.MultiPurpose;```, but does not work with ResourceBasedLocalizedEDName in properly populating the object. ```Role = Role.FromEDName("MultiPurpose");``` is the proper methodology.

### CODE REVIEW

**Comment by richardbuckle** [comment]
If the `public static readonly` members aren't suitable then let's make them private (or internal) to save our future selves from repeating the mistake.

**Comment by Hoodathunk** [comment]
As you will note in the PR, I'm removing them altogether, as they're extraneous definitions.

**Comment by richardbuckle** [comment]
On hold as I have indentified a deeper underlying issue.

**Comment by Hoodathunk** [comment]
Closing in favor of VB's Pr #887

**Pull request closed without merging**
