### PR TITLE
Enhanced SSML functionality

### PR DESCRIPTION
**Pull request by Tkael**
While studying TTS functions in EDDI, I found elements that I could clarify in support of issue #56 (as well as expanding SSML support generally). :-D

### CODE REVIEW

**Comment by richardbuckle** [comment]
I'm v keen on this too. Possibly post 2.4? I'd rather hang back and get EDDI stable with 2.4 first.
Thoughts?

**Comment by Tkael** [comment]
I sort of expected this might be held until post-2.4 simply because it is out-of-scope (and I'm ok with that). That said, I'm interested to see what people do with the new options this opens up and I don't see any real reason to hold it back either.

**Comment by richardbuckle** [comment]
I too am in favour of this but there is so much going on with 2.4 right now that I think we'd better put it on hold. Plus you prefixed it experimental.

**Comment by richardbuckle** [comment]
I too am itching to add lexicon support, as it would massively reduce reliance on the `P()` function to get things pronounced correctly. Let's try and clear all the issues rated "bug" or worse, and get all the 2.4 journal and cAPI stuff squared off, then hopefully we can get these in too.

**Comment by Tkael** [comment]
Closing to rebase and resubmit.

**Pull request closed without merging**
