### PR TITLE
Alternate Galnet feed -  v2

### PR DESCRIPTION
**Pull request by rodan123**
It seems FDEV has restored the galnet feed at `https://community.elitedangerous.com/en/galnet-rss`.
Reinstated it as the primary sourceURL, keeping `http://elitedangerous-website-backend-production.elitedangerous.com/galnet.rss` to act as a alternate source should it become unavailable again.
Revised alternateURL to fetch article GUID matching what the sourceURL uses as the article ID, so switching between sources should be seamless.

### CODE REVIEW

**Comment by richardbuckle** [comment]
Thanks for this. We are about to release 3.3.7 so will review this for 3.3.8. We also need to check with FDev which RSS feed is going to be supported so that we don't end up going in circles.

Meanwhile please could I direct you to https://github.com/EDCD/EDDI/blob/develop/docs/Contributing.md especially the section on Work in Progress conventions. Please don't merge from `develop` into your work in progress branch is it makes the commit history very confusing!

**Comment by richardbuckle** [comment]
On hold until I hear back from FDev but please proceed with review.

**Comment by richardbuckle** [comment]
FD have now confirmed that the original GalNet RSS URLs are the preferred ones going forward, so @Tkael please go ahead with reviewing this PR.

You will also need to re-enable the language pop-up that I disabled with commit ffbd8adc2377516b0eb2fb3d87d49b46bbb7fdf1

**Comment by Tkael** [comment]
Resolved "unmergeable" changelog update.
@richardbuckle I think we planned to squash and merge this PR anyways.

**Pull request merged**
