### PR TITLE
Added an indirection level to allow tests to specify different configs

### PR DESCRIPTION
**Pull request by GioVAX**
I added a variable in Constants to be used from tests code.
So we can avoid re-using our gaming environments to do debugging and running tests.

For an example of usage, see https://github.com/GioVAX/EDDI/blob/1781-Part2/Tests/MainWindowResponderTests.cs#L17

### CODE REVIEW

**Comment by richardbuckle** [comment]
Added "Needs thought" while we discuss in Discord.

**Comment by Tkael** [comment]
Confirmed that Hooda's branch includes a basic config service. Still a ways to go in refining it before it'll be ready for release, but that refinement could very probably include something like this.

**Review by Tkael — APPROVED** [review]
This will work for me until we have a robust configuration management service.

**Comment by Tkael** [comment]
Note: This is also incorporated into #1996. If #1996 is merged, this PR is no longer needed.

**Comment by richardbuckle** [comment]
I don't think this is a good way to go.

**Pull request closed without merging**
