### PR TITLE
Fix 198

### LINKED ISSUE #198: WR and type O stars have zero age in journal file
## Steps to reproduce

1. Scan a WR (Wolf-Rayet) or class O star

## Expected
EDDI reports a sensible age for the star

## Observed
EDDI reports "this is a very old star of 0 years, making it one of the youngest stars in the universe"

## Investigation
From CMDR Cometborne:

    Bug in the journal data, gives an age of 0 years.  O class stars have the same issue

````
{
  "timestamp": "2017-10-31T12:13:39Z",
  "event": "Scan",
  "BodyName": "Nuekuae AA-A h17",
  "DistanceFromArrivalLS": 0.0,
  "StarType": "WO",
  "StellarMass": 102.738281,
  "Radius": 5208460288.0,
  "AbsoluteMagnitude": -3.399948,
  "Age_MY": 0,
  "SurfaceTemperature": 14040.0,
  "Luminosity": "I",
  "RotationPeriod": 223242.609375,
  "AxialTilt": 0.0
}

{
  "timestamp": "2017-10-31T12:47:14Z",
  "event": "Scan",
  "BodyName": "Nuekuae AA-A h86 C",
  "DistanceFromArrivalLS": 15646.336914,
  "StarType": "WC",
  "StellarMass": 44.355469,
  "Radius": 6626628096.0,
  "AbsoluteMagnitude": -3.255035,
  "Age_MY": 0,
  "SurfaceTemperature": 12039.0,
  "Luminosity": "I",
  "SemiMajorAxis": 3529612460032.0,
  "Eccentricity": 0.017943,
  "OrbitalInclination": 19.946724,
  "Periapsis": 184.972382,
  "OrbitalPeriod": 404580384.0,
  "RotationPeriod": 293815.5,
  "AxialTilt": 0.0
}
{
  "timestamp": "2017-10-31T17:28:56Z",
  "event": "Scan",
  "BodyName": "Stuelou DL-Y g43",
  "DistanceFromArrivalLS": 0.0,
  "StarType": "O",
  "StellarMass": 24.40625,
  "Radius": 4900464640.0,
  "AbsoluteMagnitude": -7.720337,
  "Age_MY": 0,
  "SurfaceTemperature": 39133.0,
  "Luminosity": "Vz",
  "RotationPeriod": 204803.234375,
  "AxialTilt": 0.0
}
````

Proposal: if `Age_MY` is 0 then disregard it. We would need to amend scripts to test if reportbody.age is void.

### PR DESCRIPTION
**Pull request by richardbuckle**
Fixes #198

### CODE REVIEW

**Comment by Tkael** [comment]
`|elif reportbody.stellarclass[0] = "D":` isn't valid in cottle. Submitted a revision to correct that.

Also, Wolf-Rayet stars are rare enough that I think they merit a little more TLC. My revision makes the descriptions a little more descriptive.

**Comment by richardbuckle** [comment]
Looks like there is some test data left in that commit, I'll look at it properly later today.

**Comment by Tkael** [comment]
Yes there is. Sorry about that. I can fix it this evening if you haven't already taken care of it.

**Comment by richardbuckle** [comment]
I have pushed some more fixes including a big one where we weren't converting `reportbody.age` from millions of years to years! Please re-review.

**Pull request merged**
