### PR TITLE
Fix timestamp parsing munging timestamps

### LINKED ISSUE #1571: Munged timestamps in EDDN commodity/shipyard/outfitting messages
https://github.com/EDCD/EDDI/blob/493b03e74f23e4aa46918f4cd4692815fd2b54bb/EDDI/MarketInfoReader.cs#L12

Without `System.Globalization.DateTimeStyles.AdjustToUniversal`, this converts the timestamp to local time.  This is resulting in about 30% of EDDI's Commodity messages (and likely Shipyard and Outfitting messages as well) having munged timestamps.

### PR DESCRIPTION
**Pull request by klightspeed**
This should fix #1571

### CODE REVIEW

**Comment by klightspeed** [comment]
FYI, `DateTime.Parse(..., DateTimeStyles.AdjustToUniversal)` outputs UTC without converting to local time, while `DateTime.Parse(...).ToUniversalTime()` converts to local time then back to UTC.

The latter will be ambiguous in the hour before and after the clock is wound back in DST timezones.

**Comment by Tkael** [comment]
Ahh, TIL. :muscle:

**Comment by Tkael** [comment]
You know, we don't care about the string outside of these classes so I think `        public DateTime timestamp { get; set; }` is all we need. The property will be deserialized to UTC automatically.

**Comment by Tkael** [comment]
Placing on hold due to PR #1573.

**Comment by richardbuckle** [comment]
Thanks for the push! This is now superseded by #1573.

**Pull request closed without merging**
