### PR TITLE
Run actions to update the shipmonitor in the dispatcher thread.

### PR DESCRIPTION
**Pull request by Tkael**
Fix for #305. Verified that shipmonitor.json is being updated, EDDI's UI is being updated, and that no exceptions are thrown. :-)

### CODE REVIEW

**Comment by Tkael** [comment]
Hmm. I've found a an exception still associated with the loadout event. 
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at EddiShipMonitor.ShipMonitor.AddShip(Ship ship) in [Repo]\EDDI\ShipMonitor\ShipMonitor.cs:line 856
   at EddiShipMonitor.ShipMonitor.handleShipLoadoutEvent(ShipLoadoutEvent event) in [Repo]\EDDI\ShipMonitor\ShipMonitor.cs:line 436
   at EddiShipMonitor.ShipMonitor.PreHandle(Event event) in [Repo]\EDDI\ShipMonitor\ShipMonitor.cs:line 131
   at Eddi.EDDI.OnEvent(Event event) in [Repo]\EDDI\EDDI.cs:line 698
```

**Comment by richardbuckle** [comment]
@Tkael I’m unclear whether this is still meant to be “on hold”. 

If not, please remove the tag and @ me and I shall test it in my morning.

**Comment by Tkael** [comment]
I'm afraid it is still on hold / not ready. It  still throws exceptions when run from VoiceAttack. I've been working the issue but haven't yet found a solution that is exceptionless for both VoiceAttack and standalone.

**Comment by Tkael** [comment]
Closing since this isn't yet ready.

**Pull request closed without merging**
