### PR TITLE
Multi monitor size position

### PR DESCRIPTION
**Pull request by BullZye54**
Big fan of EDDI. EDDI-2.4.6-b2 working well, but I have a dual monitor setup and the saved window position/size would always render on the primary monitor, instead of the second monitor where EDDI and/or VoiceAttack are usually run from.

Hope this code (or portions) can help move the EDDI project forward.

### CODE REVIEW

**Comment by Tkael** [comment]
Thanks. Will evaluate once I return from my Christmas break, but this looks nice. 🙂

**Comment by BullZye54** [comment]
Thanks for considering it. Have a happy New Year!

**Comment by BullZye54** [comment]
Sorry, wrong button press...

**Comment by Tkael** [comment]
Hmm. This resolves #319 but it also removes some of the safeguards that we had built into this feature (for example, monitoring the screen resolution in case in changes between sessions. Or establishing minimum bounds for the starting height and width of the application. 

Is there a reason not to preserve those safeguards?

**Comment by BullZye54** [comment]
The isWindowVisible method tests all active displays to see if the saved window rectangle would be visible within one of the display's desktop boundary. If it's not, then the Window default size and position would be used, which is usually the upper left corner of the primary display. If that doesn't happen, it's easy to add our own default size and position, such as 40, 40, 800, 600.

**Comment by Tkael** [comment]
Pushed some changes to:
- Establish the designed height and width. 
- Make the designed height and width the minimum as long as the screen supports it.
- If the default window size and position are not valid, revert to default values rather than leaving it up to the OS.
- Make sure that the application is completely visible on-screen (rather than checking for partial visibility on-screen). Note that this allows EDDI to be shared between screens but disallows EDDI being partially off-screen.
Please review and let me know if you have any concerns? I've tested these revisions with a secondary display and against #319, but maybe you'll spot something I missed.

**Comment by BullZye54** [comment]
No issues encountered. I understand now what you were looking for regarding when to revert to the windows's designed default size.

**Pull request merged**
