### PR TITLE
Fix BodyDetails () function in Cottle not reporting Material correctly.

### PR DESCRIPTION
**Pull request by Tkael**
Also fix rings not being reported correctly.
Issue reported by gdt in EDCD/EDDI discord.

### CODE REVIEW

**Comment by Tkael** [comment]
dagnamit. Apparently, this fix breaks things in the other direction. 
@richardbuckle Your thoughts?

**Comment by richardbuckle** [comment]
Difficult timing as I have house guests today and tomorrow but I’ll try to find time to take a look.

**Comment by Tkael** [comment]
Possibly fixable by using `OnDeserialized`, but I'm starting to think we should simply roll this into the changes we are planning with #97 (since that will heavily change this area of the codebase anyways).

**Comment by Tkael** [comment]
Closing in favor of WIP branch.

**Pull request closed without merging**
