### PR TITLE
(Partial?) fix for Frontier API not connecting

### LINKED ISSUE #1786: Frontier API / CAPI: Registration callback tries a new instance of EDDI rather than the current one
1 Launch EDDI
2 Press Windows+R and supply "eddi:test" OR
3.1 Reset or log in to the Frontier API
3.2 Complete the browser with valid details.

Expected:
The URL protocol is invoked on the current EDDI instance.

Observed:
The URL protocol is invoked on a second EDDI instance which falls foul of the single-instance mutex.

### PR DESCRIPTION
**Pull request by Tkael**
May resolve #1786.

### CODE REVIEW

**Comment by richardbuckle** [comment]
Thanks @Tkael. Any thoughts on what the underlying problem is? I'm at a bit of a loss.

**Comment by GioVAX** [comment]
I have the same feeling as Richard, but this fix is urgent, and if it's working it's good for me!

**Review by GioVAX — APPROVED** [review]

**Comment by richardbuckle** [comment]
Yeah but I don't like mysteries. Past experience has taught me that unsolved mysteries return to bite you later on.

**Comment by richardbuckle** [comment]
It's a beta, so I'm happy to take a bit of time.

**Comment by GioVAX** [comment]
I agree: this is something we must get to the bottom of.

**Comment by Tkael** [comment]
I haven't yet identified a cause either.

**Pull request merged**
