### PR TITLE
Fix Inara tests

### LINKED ISSUE #1766: Revise `InaraTests.cs` to use a mock object
Tests are best when they are completely independent of the user's account and the status of any network services. 

Please look into revising `InaraTests.cs` to use a mock object for the actual Inara service.

### PR DESCRIPTION
**Pull request by Tkael**
Resolves #1766.

### CODE REVIEW

**Comment by richardbuckle** [comment]
@GioVAX Another deep end for you! I'm confident you can navigate it.

**Comment by GioVAX** [comment]
LGTM.

I remember using FluentAssertions a couple of years ago to perform recursive object comparisons. Is this some we could consider using?
It would make the test more expressive, and would also future proof the test in case we add a new property and forget to extend the test for it.

**Comment by Tkael** [comment]
Interesting thought. I'm not familiar with FluidAssertions but Google tells me that it's a fairly popular dependency that is used for writing unit tests.
Can you elaborate on how you think it would add value to this project?

**Comment by GioVAX** [comment]
First of all, I haven't used FluentAssertions recently, so this might be out-of-date 😁 

In this specific test for Inara, the whole code would become something like this:
```
var expectedCmdrs = new List<InaraCmdr>() {new InaraCmdr {
     username = "Artie",
     id = 1,
     ...
     commanderranks = new List<CommanderRank>() { 
           new CommanderRank { rank = "trade", rankvalue = 8, ... },
           new CommanderRank { rank = "exploration", rankvalue = 2, ... },
     },
     ...
     } };

List<InaraCmdr> inaraCmdrs = 
           DeserializeJsonResource<List<InaraCmdr>>(Resources.inaraCmdrs);

inaraCmdrs.Should().BeEquivalentTo(expectedCmdrs);
```

`expectedCmdrs` might be initialized just once for all the tests that use `Resources.inaraCmdrs`.

The added value for the project is two-fold.
1. the test is simpler to write and is more expressive
2. added security IF we forget to update the test code when a new property is added to `InaraCmdr`:
with the current implementation, the test will still pass, but we are not actually testing that the new property is correctly parsed. With `BeEquivalentTo` the test will fail and will tell which property we have not initialized.

More broadly, FluentAssertions transform the whole assertions in a way that is similar to common speaking.
This is a sample from their docs:
```
string actual = "ABCDEFGHI";
actual.Should()
    .StartWith("AB")
    .And.EndWith("HI")
    .And.Contain("EF")
    .And.HaveLength(9);
```

**Comment by Tkael** [comment]
As far as changes to the definition of InaraCmdr is concerned... if the definition changes then there's a good chance that `List<InaraCmdr> inaraCmdrs = DeserializeJsonResource<List<InaraCmdr>>(Resources.inaraCmdrs);` will throw an exception on the canned data. I'll add a commit to wrap this in a try-catch statement.

We do already have a (more basic) extension method for comparing objects in the repo at Utilities/ExtensionMethods.cs. I'll convert the test to use this method.

**Review by GioVAX — COMMENTED** [review]
Nice.

**Review by GioVAX — APPROVED** [review]
Forgot to select "Approve" :)

**Comment by GioVAX** [comment]
Just to add a bit more context about FluentAssertion.

In the "add a property to InaraCmndr" scenario, I was thinking to the following situation:
-  add a property to InaraCmndr
- update DeserializeJsonResource<>
- forget to add the new property to the test
Add a little evil twist 😈: the code added in DeserializeJsonResource has a bug.

OTOH, the FluentAssertion BeEquivalentTo will use reflection to test every field and property of the object, so, in the scenario above, the new property will actually be checked.

**Review by richardbuckle — APPROVED** [review]

**Pull request merged**
