### PR TITLE
Implement carrier jump related events for Elite v3.7

### PR DESCRIPTION
**Pull request by Tkael**
From the journal manual, v28:
✔️ 11.1 CarrierJumpedEvent
✔️ 11.4 CarrierJumpRequestEvent
✔️ 11.16 CarrierJumpCancelledEvent

Include synthetic, timer based events for:
- CarrierPadsLockedEvent
- CarrierJumpEngagedEvent
- CarrierCooldownEvent

Please play attention to state tracking when testing and verify that it is robust.
Event scripts are subject to change, please provide feedback.

### CODE REVIEW

**Comment by richardbuckle** [comment]
Testing for you.

**Comment by richardbuckle** [comment]
Location event doesn't recongise that I'm on a carrier.
Steps: dock at an FC and relog.
Expected: You are docked at the Fleet Carrier, "Sharras Gift" on Skeggiko O A 1 in the Skeggiko O system.
Observed: You are docked at the Unknown Station, G 53-K 3Q on Skeggiko O A 1 in the Skeggiko O system.

JSON
```json
{
  "timestamp": "2020-05-19T22:04:41Z",
  "event": "Location",
  "Docked": true,
  "StationName": "G53-K3Q",
  "StationType": "FleetCarrier",
  "MarketID": 3700571136,
  "StationFaction": {
    "Name": "FleetCarrier"
  },
  "StationGovernment": "$government_Carrier;",
  "StationGovernment_Localised": "Private Ownership ",
  "StationServices": [
    "dock",
    "autodock",
    "blackmarket",
    "commodities",
    "contacts",
    "exploration",
    "crewlounge",
    "rearm",
    "refuel",
    "repair",
    "engineer",
    "flightcontroller",
    "stationoperations",
    "stationMenu",
    "carriermanagement",
    "carrierfuel",
    "voucherredemption"
  ],
  "StationEconomy": "$economy_Carrier;",
  "StationEconomy_Localised": "Private Enterprise",
  "StationEconomies": [
    {
      "Name": "$economy_Carrier;",
      "Name_Localised": "Private Enterprise",
      "Proportion": 1.0
    }
  ],
  "StarSystem": "Skeggiko O",
  "SystemAddress": 9467584390577,
  "StarPos": [
    53.6875,
    11.9375,
    16.5
  ],
  "SystemAllegiance": "Federation",
  "SystemEconomy": "$economy_Agri;",
  "SystemEconomy_Localised": "Agriculture",
  "SystemSecondEconomy": "$economy_Colony;",
  "SystemSecondEconomy_Localised": "Colony",
  "SystemGovernment": "$government_Corporate;",
  "SystemGovernment_Localised": "Corporate",
  "SystemSecurity": "$SYSTEM_SECURITY_high;",
  "SystemSecurity_Localised": "High Security",
  "Population": 4153430104,
  "Body": "Skeggiko O A 1",
  "BodyID": 3,
  "BodyType": "Planet",
  "Powers": [
    "Felicia Winters"
  ],
  "PowerplayState": "Controlled",
  "Factions": [
    {
      "Name": "Eta Crucis Future",
      "FactionState": "None",
      "Government": "Democracy",
      "Influence": 0.064935,
      "Allegiance": "Federation",
      "Happiness": "$Faction_HappinessBand2;",
      "Happiness_Localised": "Happy",
      "MyReputation": 0.0
    },
    {
      "Name": "Workers of Skeggiko O Labour",
      "FactionState": "None",
      "Government": "Democracy",
      "Influence": 0.136863,
      "Allegiance": "Federation",
      "Happiness": "$Faction_HappinessBand2;",
      "Happiness_Localised": "Happy",
      "MyReputation": 0.0
    },
    {
      "Name": "Skeggiko O Jet Natural Inc",
      "FactionState": "None",
      "Government": "Corporate",
      "Influence": 0.036963,
      "Allegiance": "Independent",
      "Happiness": "$Faction_HappinessBand2;",
      "Happiness_Localised": "Happy",
      "MyReputation": 0.0
    },
    {
      "Name": "Skeggiko O Law Party",
      "FactionState": "None",
      "Government": "Dictatorship",
      "Influence": 0.063936,
      "Allegiance": "Independent",
      "Happiness": "$Faction_HappinessBand2;",
      "Happiness_Localised": "Happy",
      "MyReputation": 0.0
    },
    {
      "Name": "Green Party of LFT 926",
      "FactionState": "None",
      "Government": "Democracy",
      "Influence": 0.155844,
      "Allegiance": "Federation",
      "Happiness": "$Faction_HappinessBand2;",
      "Happiness_Localised": "Happy",
      "MyReputation": 100.0
    },
    {
      "Name": "Skeggiko O Blue Electronics Corp",
      "FactionState": "None",
      "Government": "Corporate",
      "Influence": 0.496504,
      "Allegiance": "Federation",
      "Happiness": "$Faction_HappinessBand2;",
      "Happiness_Localised": "Happy",
      "MyReputation": 0.0
    },
    {
      "Name": "United Skeggiko O Defence Party",
      "FactionState": "None",
      "Government": "Dictatorship",
      "Influence": 0.044955,
      "Allegiance": "Independent",
      "Happiness": "$Faction_HappinessBand2;",
      "Happiness_Localised": "Happy",
      "MyReputation": 0.0
    }
  ],
  "SystemFaction": {
    "Name": "Skeggiko O Blue Electronics Corp"
  }
}
```

**Comment by richardbuckle** [comment]
Holy crap the location event doesn't have the station name.

**Comment by richardbuckle** [comment]
Hmm, other events are correcly saying "Fleet Carrier".

**Comment by richardbuckle** [comment]
Pad lockdown fires too early.

**Comment by Tkael** [comment]
@richardbuckle I set the timing at 200 seconds prior to the scheduled jump based on a comment someone made but that is readily adjusted. How far off is it?

**Comment by Tkael** [comment]
Huh. Apparently we're not updating the station model when we handle Location events. I'll push a new commit to this PR to improve that...

**Comment by Tkael** [comment]
I've made some measurements of the timing and pushed some new commits. Should be significantly better now.

**Comment by Tkael** [comment]
Unfortunately, none of the events that I'm looking at provide the name "Sharras Gift".

**Comment by richardbuckle** [comment]
@Tkael apologies, I accidentally over-wrote your comment when I wanted to reply. Not sure how I even had permission for that.

**Comment by richardbuckle** [comment]
Will re-test timings tomorrow but I'm confident you've got this.

**Comment by Tkael** [comment]
I think that was a comment about how "Sharra's Gift" was nowhere to be found in the journal entries that I was looking at. 

At this point I'm feeling pretty confident about the timings and am most concerned about making sure that we're handling the global state changes as well as we can.

**Comment by richardbuckle** [comment]
It's good.

**Pull request merged**
