### PR TITLE
Feature - Body and Star Scan Values

### PR DESCRIPTION
**Pull request by andre-arsenault**
Re-forked from https://github.com/cmdrmcdonald/EliteDangerousDataProvider/pull/274

Does not include the 50% bonus for first discovery, as the "discovered by" information is not currently available in the journal events.

Credit for the scan value formulae goes to MattG from this thread: https://forums.frontier.co.uk/showthread.php/232000-Exploration-value-formulae

Thanks to Tkael for suggesting various improvements to the original pull request.

### CODE REVIEW

**Comment by Tkael** [comment]
Now that I have a better handle on EDDI's codebase, I think I can incorporate this into the event data (e.g. event.estimatedvalue). Mind if I give it a try?

**Comment by andre-arsenault** [comment]
Please do! That would be the ideal way to do this, so we only handle the TTS output in the personality scripts.

**Comment by Tkael** [comment]
A quick update. I now have a working version of the code that gives estimated scan values via event.estimatedvalue. I've got a few other enahncements in mind though before I send in the final pull request. o7

**Comment by Tkael** [comment]
Closing, incorporated on pull request #220. :-)

**Pull request closed without merging**
