### PR TITLE
Fix for #193, EDSM comments not read

### PR DESCRIPTION
**Pull request by Tkael**
Bugfix for #193. Adds a function that is called at EDDI startup to asynchronously update EDSM comments as well as any flight logs since the last EDSM sync.
(Note that it may take a few minutes from the time a comment is posted on EDSM to when when it will be available for retrieval)

The function can optionally be revised to be called at events if preferred (possibly location events?), but I thought this method best for making sure EDSM data is up to date without slowing down events or overwhelming the EDSM server.

### CODE REVIEW

**Comment by richardbuckle** [comment]
At first sight this introduces a dependency from EddiStarMapService on EddiDataProviderService. 
If possible, I would like to find a refactored solution that doesn't create such a dependency.

I don't feel qualified to approve this on my own, need input by @Hoodathunk please.

**Comment by richardbuckle** [comment]
I'm not *against* this, but I do worry that I don't have a good handle on the dependency graph here. 

Let's please step back and get that defined.

**Comment by Tkael** [comment]
How would one go about generating a dependency graph? I've searched, but short of actually _paying_ for VS, I'm not seeing an easy solution.

**Comment by richardbuckle** [comment]
I've reached the same conclusion, dependency graphs are behind a paywall in VS, as are test coverage tools. Rather annoying as both are crucial tools for developers taking on maintenance of legacy projects.

**Comment by richardbuckle** [comment]
Leaving aside my desire to get a handle on the dependency tree, this fix appears good.

**Pull request merged**
