### PR TITLE
Replace the definition "StationLargestPad" with the more generalize definition "Size".

### PR DESCRIPTION
**Pull request by Tkael**
Extend to cover ship sizes as well as landing pad sizes.
Please review and merge prior to #1423.

### CODE REVIEW

**Comment by Tkael** [comment]
Hmm... this was supposed to target the same branch as #1423. In it's current state, it actually includes #1423 and takes things a step further.

**Comment by richardbuckle** [comment]
The resource renaming is going to mean unnecessary busy-work on CrowdIn, so I'll rework this to avoid that. Also I feel the name `Size` is too general.

**Comment by Tkael** [comment]
Size is quite general, I agree. I wanted a flexible definition that could be applied to various objects with size. Happy to consider any alternatives you want to put forward. 🙂

**Comment by richardbuckle** [comment]
I'd say LandingPadSize. Rework in progress.

**Comment by richardbuckle** [comment]
Closing as superseded.

**Comment by Tkael** [comment]
That's a little less generic than I was hoping for... I thought we might extend it to cover needlepoint sizes too (which is why I included tiny and huge).

**Comment by richardbuckle** [comment]
I don't see any merit in conflating sizes of landing pads vs hardpoints: on the contrary they are fundamentally different, and type safety exists precisely to stop us from conflating them. Just because they have the same names doesn't mean they're the same thing.

**Pull request closed without merging**
