### PR TITLE
Update Cottle version

### LINKED ISSUE #1687: Cottle version is out of date
## EDDI version in which issue is found
3.5.3

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
1. Visit https://github.com/r3c/cottle and note the release number
2. Visit the recently revised Cottle documentation page at https://cottle.readthedocs.io/. Note that the documents there (with the exception of the update guide) only describe the latest version and not version 1.4.0.4 (the version EDDI currently uses).

## Expected
Cottle documentation available on the internet matches EDDI's implementation

## Observed
Differences may develop since EDDI is using Cottle version 1.4.0.4 while the latest stable release is 1.6.0.

## Investigation
Cottle version 1.4.0.4 was the last version prior to Cottle rolling to a requirement for .Net version 4.7.2. Updating would require 
1. Retargeting from [.Net version 4.7.1 to 4.7.2](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/retargeting/4.7.1-4.7.2).
2. Updating the Cottle package and following [the documented versioning update guide](https://cottle.readthedocs.io/en/stable/page/07-version.html#update-from-previous).

### PR DESCRIPTION
**Pull request by Tkael**
Resolves #1687.

### CODE REVIEW

**Review by richardbuckle — APPROVED** [review]
Taking this on trust.

**Review by richardbuckle — CHANGES_REQUESTED** [review]
I can't resolve the merge conflicts here. I recommend closing this and opening a new one once the dust has settled

**Comment by Tkael** [comment]
Will do.

**Comment by Tkael** [comment]
Closing to rebase.

**Pull request closed without merging**
